"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0A0F1E] pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-6">
        <Link href="/" className="inline-flex items-center gap-2 text-zinc-500 hover:text-white transition-colors mb-12 group">
          <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          Back to Home
        </Link>

        <div className="bg-zinc-900/10 border border-white/[0.08] rounded-[40px] p-8 md:p-12 backdrop-blur-sm">
          <h1 className="text-4xl font-extrabold text-white mb-4" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>Privacy Policy</h1>
          <p className="mb-12 text-zinc-500 font-medium tracking-tight uppercase text-xs">Last updated: April 2026</p>

          <div className="space-y-12 text-zinc-400 leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold text-white mb-4">1. Introduction</h2>
              <p>
                Resodin Inc. ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share your personal information when you use our LinkedIn content generation platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">2. Data We Collect</h2>
              <div className="space-y-4">
                <p>
                  <strong className="text-white">Account Information:</strong> We collect your name, email address, and authentication data via Clerk when you create an account.
                </p>
                <p>
                  <strong className="text-white">Content Data:</strong> We collect the LinkedIn posts you upload to create your Voice DNA and the content generated by our AI. This data is used solely to provide and improve our services for you.
                </p>
                <p>
                  <strong className="text-white">Usage Data:</strong> We collect anonymous data about how you interact with our application to improve performance and user experience.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">3. How We Use Data</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our service.</li>
                <li>To personalize your experience and train your individual Voice DNA models.</li>
                <li>To process payments via Razorpay.</li>
                <li>To communicate with you regarding support or platform updates.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">4. Third-Party Services</h2>
              <p>
                We use trusted third-party services including Clerk (Auth), Supabase (Database), Razorpay (Payments), and Google Generative AI (Content Processing). These services have their own privacy policies.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white mb-4">5. User Rights</h2>
              <p>
                You have the right to access, update, or delete your personal data at any time through your account settings or by contacting us directly at <a href="mailto:support@resodin.ai" className="text-[#00E5FF] hover:underline">support@resodin.ai</a>.
              </p>
            </section>
          </div>

          <div className="mt-20 pt-12 border-t border-white/[0.08] text-center">
            <p className="text-zinc-500 italic text-sm">
              If you have any questions about this Privacy Policy, please contact us.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
