import React from "react";

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20 text-zinc-300 leading-relaxed">
      <h1 className="text-4xl font-extrabold text-white mb-4" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>Privacy Policy</h1>
      <p className="mb-12 text-zinc-500 font-medium tracking-tight uppercase text-xs">Last updated: April 2026</p>

      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-4">1. Introduction</h2>
        <p className="mb-4">
          Resodin Inc. ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share your personal information when you use our LinkedIn content generation platform.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-4">2. Data We Collect</h2>
        <p className="mb-4">
          <strong>Account Information:</strong> We collect your name, email address, and authentication data via Clerk when you create an account.
        </p>
        <p className="mb-4">
          <strong>Content Data:</strong> We collect the LinkedIn posts you upload to create your Voice DNA and the content generated by our AI. This data is used solely to provide and improve our services for you.
        </p>
        <p className="mb-4">
          <strong>Usage Data:</strong> We collect anonymous data about how you interact with our application to improve performance and user experience.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-4">3. How We Use Data</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>To provide and maintain our service.</li>
          <li>To personalize your experience and train your individual Voice DNA models.</li>
          <li>To process payments via Razorpay.</li>
          <li>To communicate with you regarding support or platform updates.</li>
        </ul>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-4">4. Third-Party Services</h2>
        <p className="mb-4">
          We use trusted third-party services including Clerk (Auth), Supabase (Database), Razorpay (Payments), and Google Generative AI (Content Processing). These services have their own privacy policies.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white mb-4">5. User Rights</h2>
        <p className="mb-4">
          You have the right to access, update, or delete your personal data at any time through your account settings or by contacting us directly at <a href="mailto:support@resodin.ai" className="text-[#00E5FF] hover:underline">support@resodin.ai</a>.
        </p>
      </section>

      <div className="pt-12 border-t border-white/[0.08] text-center">
        <p className="text-zinc-500 italic text-sm">
          If you have any questions about this Privacy Policy, please contact us.
        </p>
      </div>
    </div>
  );
}
